### ISSUE TITLE
cmd/govim: recent x/tools, gopls upgrade emits extra junk in omnicompletion

### ISSUE THREAD

**Issue by cespare** [govim/govim#658] opened 2020-01-08 06:42 UTC
After 11eb9c75ea607c4caf63a93e2d8016b2c0099c8f (#652, "deps: upgrade x/tools and gopls to 774c71fc") omnicompletion includes some extra markup text:

```
	mac := hmac.New(sha256.New, []byte(key))
	mac.Su<hit C-x C-o or whatever to omnicomplete here>
```

yields

```
	mac := hmac.New(sha256.New, []byte(key))
	mac.Sum(${1:})
```

Before that change, it would just complete the name of the function:

```
	mac := hmac.New(sha256.New, []byte(key))
	mac.Sum
```

**Comment by cespare** [comment] 2020-01-08 06:42
Ugh, hit enter too early. Editing in details now...

**Comment by myitcv** [comment] 2020-01-08 09:52
Thanks for the report. 

I spotted this last night but was hoping I'd be able to squeeze in a fix before anyone noticed.

The back story is:

* we upgrade `x/tools` and `gopls` in 11eb9c75ea607c4caf63a93e2d8016b2c0099c8f
* I spotted the bug immediately and Rebecca quickly raised and merged https://go-review.googlesource.com/c/tools/+/213640 as a fix
* the problem is that in the intervening time https://go-review.googlesource.com/c/tools/+/212102 had been merged which introduced another bug
* https://go-review.googlesource.com/c/tools/+/213641 was quickly raised to fix that but it transpires the fix will take long

Hence I've now:

* raised https://github.com/govim/govim/pull/659 to test coverage of this sort of completion
* raised https://github.com/govim/govim/pull/660 to upgrade `x/tools` and `gopls` to a temp fork where this bug is fixed

**Comment by cespare** [comment] 2020-01-08 09:58
Thanks for the info! And no worries, I expect to encounter stuff like this when I keep using master.

**Comment by myitcv** [comment] 2020-01-08 10:01
We shouldn't really have this sort of stuff in master though to my mind. Because most Vim plugin managers/approaches effectively default to using master (as opposed to released versions) we need to be a bit more careful.

**Closed** 2020-01-08 11:05 UTC
